<script src="/js/jquery.jeditable.js" type="text/javascript"></script>
<style type="text/css">  

    #content {
      width: 770px;
    }

    .editable input[type=submit] {
      color: #F00;
      font-weight: bold;
    }
    .editable input[type=button] {
      color: #0F0;
      font-weight: bold;
    }
</style>
<script type="text/javascript"> 
    $(function() {

      $(".edit_area").editable("http://hashkit.com/Pages/hash_function", { 
          type   : 'textarea',
          select : true,
          submit : 'Ok',
          cancel : 'Cancel'
      });
    });
</script>

<article class="container">
        <div class="row">
            <div class="col-md-3" id="leftCol">
                <ul class="nav nav-stacked" id="sidebar">
                  <li><a href="#sec0" class="">Introduction</a></li>
                  <li><a href="#sec1" class="">Types of Hash functions</a></li>
                  <li><a href="#sec2" class="">Hash functions' properties</a></li>
                  <li><a href="#sec3" class="">Attacks on Hash functions</a></li>
                  <li><a href="#sec4" class="">Summary</a></li>
              </ul>
          </div>
          <div class="col-md-9">
              <h2 id="sec0" class="edit_area" contenteditable="false">Introduction</h2>
              <br>
              <h3 class="">What is a hash function ?</h3>
              <br>
              A hash function takes in any length of data such as characters and maps them to a fixed length of arbitrary hash value.
              <br>
                <h3 class="">What about crytographic hash function ?</h3>
                <br>
                Despite of having the same functionality as a hash function, it has additional properties such one-way which provides better security. It is usually associated with generating a message digest (sometimes called a checksum) which is normally shorter than the original data. For a message digest function to be crypotgraphically secure, it must be computationally infeasible to get back the original message by using the message digest and impossible to find two different messages with the same message digest.
                <br>
                <br>
                Example for a MD5 function to perform on a message :
                <br>
                <br>
                  <img src="/img/example.jpg">
                <br>
                <br>
                <h3>Is there encryption in hash or digest ?</h3>
                <br>
                No, There is always a cofusion because all these words are in the category of "cryptography", but it is important to understand the difference. Encryption
                provide a 1:1 mapping between an arbitrary length and output and can be always reversible with a key which makes it a two-way operation.     
                <br>
                <div class="row">
                  <div class="col-md-6">
                      <div class="panel panel-default">
                          <div class="panel-heading">
                              <h3 class="" contenteditable="false">Encryption</h3>
                              <img src="">
                          </div>
                      </div>
                  </div>
                  <div class="col-md-6">
                      <div class="panel panel-default">
                          <div class="panel-heading">
                              <h3 class="" contenteditable="false">Hash Function</h3>
                              <img src="">
                          </div>
                      </div>
                  </div>
              </div>
              <br>

              <h3 class="">Usage of crytographic hash functions</h3>
              <br>
              <h3>Verifying file integrity</h3>
              <br>
              This is often used to check the intergity of the data by comparing the both checksums of two identical files generated by same hash function to be similar to one another.
              <br>
              <h3>Hashing passwords</h3>
              <br>
              In a computer system, it is not a good idea to store passwords in cleartext (readable to user) due to the fact that if the system has been compromised, the bad guy can somehow obtain the stored passwords and use to their advantage. Hence, a more secure way is to store the hash of the password, rather than the password itself since the hashes are not reversible. This reduces the consequence of damage done by the bad guy.
              Example : 
              <br>
              <br>  
              </br>
              <hr class="col-md-12">
                <h2 id="sec1" class=""></h2>

              <p class="">Rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto
                  beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas
                  sit aspernatur aut odit aut.</p>
              <div class="row">
                  <div class="col-md-6">
                      <div class="panel panel-default">
                          <div class="panel-heading">
                               <h3 class="">Hello.</h3>

                          </div>
                          <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra
                              varius quam sit amet vulputate. Quisque mauris augue, molestie tincidunt
                              condimentum vitae, gravida a libero. Aenean sit amet felis dolor, in sagittis
                              nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor
                              accumsan. Aliquam in felis sit amet augue.</div>
                      </div>
                  </div>
                  <div class="col-md-6">
                      <div class="panel panel-default">
                          <div class="panel-heading">
                               <h3 class="">Hello.</h3>

                          </div>
                          <div class="panel-body">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis pharetra
                              varius quam sit amet vulputate. Quisque mauris augue, molestie tincidunt
                              condimentum vitae, gravida a libero. Aenean sit amet felis dolor, in sagittis
                              nisi. Sed ac orci quis tortor imperdiet venenatis. Duis elementum auctor
                              accumsan. Aliquam in felis sit amet augue.</div>
                      </div>
                  </div>
              </div>
              <hr class="">
                <h2 id="sec2" class="">Hash functions' properties</h2>

              <p class="">A cyptographic hash functions must be able to defend against all known type of cryptanalytic attack. It should be able to apply to any input size and output a fixed size. It must have the following properties:
                  <li><b>Pre-image resistance</b>
                  <br>
                  For any given input Y, it should be difficult to find another input X such that hash(Y) = hash(X) and Y not equals to X. Function that does not have this property are prone to preimage attacks.
                  <br><br>
                  <li><b>Second pre-image resistance</b>
              
              </p>
              <div class="row">
                  <div class="col-md-4">
                      <img src="//placehold.it/300x300" class="img-responsive">
                  </div>
                  <div class="col-md-4">
                      <img src="//placehold.it/300x300" class="img-responsive">
                  </div>
                  <div class="col-md-4">
                      <img src="//placehold.it/300x300" class="img-responsive">
                  </div>
              </div>
              <hr class="">
                <h2 id="sec3" class="">Section 3</h2>
  Images are responsive sed @mdo but sum are more fun peratis unde omnis
              iste natus error sit voluptatem accusantium doloremque laudantium, totam
              rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto
              beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas
              sit aspernatur aut odit aut fugit, sed quia cor magni dolores eos qui ratione
              voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum
              quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam
              eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.
              Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit
              laboriosam, nisi ut..
              <br class="">Fos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui
              dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia
              non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam
              quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem
              ullam corporis suscipit laboriosam, nisi ut..
                <h2 id="sec4" class="">Section 4</h2>
  Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium
              doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore
              veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim
              ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia
              cor magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro
              quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci
              velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore
              magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum
              exercitationem ullam corporis suscipit laboriosam, nisi ut
              <hr class="">
               <h4 class=""></h4>

              <hr class="">
          </div>
      </div>
  </article>

<script type="text/javascript">
    $('#sidebar').affix({
        offset: {
          top: 235
        }
    });
    var $body   = $(document.body);
    var navHeight = $('.navbar').outerHeight(true) + 10;

    $body.scrollspy({
      target: '#leftCol',
      offset: navHeight
    });

    /* smooth scrolling sections */
    $('a[href*=#]:not([href=#])').click(function() {
        if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
          var target = $(this.hash);
          target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
          if (target.length) {
            $('html,body').animate({
              scrollTop: target.offset().top - 50
            }, 1000);
            return false;
          }
        }
    });


</script>